substitutions:
  name: athom-smart-plug-v3-f8b6a0
  friendly_name: Athom Plug V3 f8b6a0
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: W8ea0iCm2xDBpwtn9QVKgVhHbkzuwlwArrjcnPIYb/4=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
