substitutions:
  name: athom-smart-plug-v3-f986c0
  friendly_name: Athom Plug V3 f986c0
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: jFAVBzprhljb7M3ppuoAZSMPgjmNY4eGU6HtQLeaSgA=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
