substitutions:
  name: athom-smart-plug-v3-f8c744
  friendly_name: Athom Plug V3 f8c744
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: gFhNPkq5nQaUUCtLcGqvb/sEj58KAZU6/WixJ0OksI8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
