substitutions:
  name: athom-smart-plug-v3-f986a8
  friendly_name: Athom Plug V3 f986a8
packages:
  Athom_Technology.Smart_Plug_V3: github://athom-tech/esp32-configs/athom-smart-plug.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: wDHh1FHVuQhRfRaFgpfc1w4F54rcSyTWaKVwWvDNU3Y=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
